CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(80) NOT NULL CHECK(name <> ''),
  avatar VARCHAR(80) NOT NULL CHECK(avatar <> ''),
  email VARCHAR(80) NOT NULL CHECK(email <> ''),
  password VARCHAR(80) NOT NULL CHECK(password <> ''),	
);